version: '3.8'

services:
  taskmanager.api:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManager_docker_db;User Id=${SA_USER_ID};Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: SqlServerContainer  
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD} 
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: